version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: app
    image: mamont79/home-lib-service:latest
    restart: always
    env_file: .env
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
    networks:
      app-network:
        ipv4_address: 192.168.100.100
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: db
    image: mamont79/home-lib-service:latest
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      app-network:
        ipv4_address: 192.168.100.101

volumes:
  postgres:
    name: data

networks:
  app-network:
    name: intro
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          ip_range: ${NETWORK_IP_RANGE}
          gateway: ${NETWORK_GATEWAY}
