version: '3.0'

services:
  main:
    container-name: main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  app:
    container-name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: mamont79/home-lib-service-app:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
  postgres:
    container-name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG-DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata: /var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
# version: '3'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: mamont/home-lib-service-app:latest
#     restart: unless-stopped
#     env_file: .env
#     ports:
#       - 4000:4000
#     volumes:
#       - ./src:/app/src
