version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: mamont79/home-lib-service:latest
    restart: always
    env_file: .env
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
    networks:
      app-network:
        ipv4_address: 192.168.100.100
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    image: mamont79/home-lib-service:latest
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      app-network:
        ipv4_address: 192.168.100.101

  db-ui:
    image: dpage/pgadmin4:7.5
    environment:
      PGADMIN_DEFAULT_EMAIL: 'dalhoupavel@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'mamont79'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: always
    networks:
      app-network:
        ipv4_address: 192.168.100.102
    depends_on:
      - db

volumes:
  postgres:

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          ip_range: 192.168.100.0/24
          gateway: 192.168.100.1
